// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpwbnffkmwaluqieassw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwd2JuZmZrbXdhbHVxaWVhc3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDAxMTUsImV4cCI6MjA3MzIxNjExNX0._aqXEJ6e6xZqXqfzot9EbQjEKLXBhvo1JVxxl64QV1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});